import { expect, test } from '@playwright/test'

test('browser weapons obey cooldowns, kill once and clear on restart', async ({ page }) => {
  await page.goto('/?scenario=combat')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.keyboard.down('q')
  await page.evaluate('window.__battle.advance(1/60)')
  expect(await page.evaluate<number>('window.__battle.snapshot().bullets.length')).toBe(3)
  await page.evaluate('window.__battle.advance(1/60)')
  expect(await page.evaluate<number>('window.__battle.snapshot().bullets.length')).toBe(3)
  await page.keyboard.up('q')
  await page.keyboard.down('Space')
  await page.evaluate('window.__battle.advance(0.8)')
  await page.keyboard.up('Space')
  expect(await page.evaluate<number>('window.__battle.snapshot().score')).toBe(1)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const before = await page.evaluate('window.__battle.snapshot()')
  await page.evaluate('window.__battle.advance(2)')
  expect(await page.evaluate('window.__battle.snapshot()')).toEqual(before)
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.evaluate('window.__battle.advance(180)')
  await expect(page.getByRole('button', { name: 'Play Again' })).toBeVisible()
  await page.getByRole('button', { name: 'Play Again' }).click()
  await expect(page.locator('canvas')).toBeVisible()
  expect(await page.evaluate<number>('window.__battle.snapshot().score')).toBe(0)
})

test('Shooter damages the player; death freezes the world', async ({ page }) => {
  await page.goto('/?scenario=shooter')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.evaluate('window.__battle.advance(0.6)')
  expect(await page.evaluate<number>('window.__battle.snapshot().health')).toBeLessThan(100)
  await page.evaluate('window.__battle.advance(30)')
  await expect(page.getByRole('heading', { name: 'Your ship has sunk' })).toBeVisible()
  const ended = await page.evaluate('window.__battle.snapshot()')
  await page.keyboard.down('q')
  await page.evaluate('window.__battle.advance(10)')
  await page.keyboard.up('q')
  expect(await page.evaluate('window.__battle.snapshot()')).toEqual(ended)
})

test('real multitouch can move and fire together without stuck controls', async ({ page, context }) => {
  await page.goto('/?scenario=combat')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  const movement = await page.getByRole('button', { name: 'Forward', exact: true }).boundingBox()
  const fire = await page.getByRole('button', { name: 'Fire right', exact: true }).boundingBox()
  const session = await context.newCDPSession(page)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [
    { id: 1, x: movement!.x + movement!.width / 2, y: movement!.y + movement!.height / 2 },
    { id: 2, x: fire!.x + fire!.width / 2, y: fire!.y + fire!.height / 2 },
  ] })
  await page.evaluate('window.__battle.advance(0.2)')
  expect(await page.evaluate<number>('window.__battle.snapshot().player.y')).toBeLessThan(480)
  expect(await page.evaluate<number>('window.__battle.snapshot().bullets.length')).toBe(3)
  await session.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
  const y = await page.evaluate<number>('window.__battle.snapshot().player.y')
  await page.evaluate('window.__battle.advance(0.2)')
  expect(await page.evaluate<number>('window.__battle.snapshot().player.y')).toBe(y)
})

test('keyboard movement respects island and arena bounds and rotation', async ({ page }) => {
  await page.goto('/?scenario=island')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.keyboard.down('w')
  await page.evaluate('window.__battle.advance(2)')
  await page.keyboard.up('w')
  expect(await page.evaluate<number>('window.__battle.snapshot().player.y')).toBeGreaterThanOrEqual(309)
  await page.keyboard.down('Space')
  await page.evaluate('window.__battle.advance(1/60)')
  await page.keyboard.up('Space')
  expect(await page.evaluate<number>('window.__battle.snapshot().bullets.length')).toBe(0)
  await page.keyboard.down('d')
  await page.evaluate('window.__battle.advance(0.5)')
  await page.keyboard.up('d')
  expect(await page.evaluate<number>('window.__battle.snapshot().player.angle')).toBeGreaterThan(-Math.PI / 2)
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.goto('/?scenario=arena')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.keyboard.down('w')
  await page.evaluate('window.__battle.advance(3)')
  await page.keyboard.up('w')
  const y = await page.evaluate<number>('window.__battle.snapshot().player.y')
  expect(y).toBeGreaterThanOrEqual(23)
  expect(y).toBeLessThan(27)
})

test('Chaser contact does not score and visibility pause requires resume', async ({ page }) => {
  await page.goto('/?scenario=chaser')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.evaluate('window.__battle.advance(1)')
  expect(await page.evaluate('window.__battle.snapshot().health')).toBe(75)
  expect(await page.evaluate('window.__battle.snapshot().score')).toBe(0)
  await page.keyboard.down('w')
  await page.keyboard.down('Space')

  await page.evaluate("Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange'))")
  await expect(page.getByRole('heading', { name: 'Battle paused' })).toBeVisible()
  const before = await page.evaluate('window.__battle.snapshot()')
  await page.evaluate('window.__battle.advance(3)')
  expect(await page.evaluate('window.__battle.snapshot()')).toEqual(before)
  await page.evaluate("delete document.hidden; document.dispatchEvent(new Event('visibilitychange'))")
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Battle paused' })).toBeHidden()
  await page.evaluate('window.__battle.advance(0.2)')
  expect(await page.evaluate<number>('window.__battle.snapshot().player.y')).toBe(480)
  expect(await page.evaluate<number>('window.__battle.snapshot().bullets.length')).toBe(0)
  await page.keyboard.up('w')
  await page.keyboard.up('Space')
})
