import { expect, test } from '@playwright/test'

test('HTTP, connection and timeout failures remain recoverable without blocking gameplay', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/?scenario=arena')
  for (const scenario of ['http-400', 'http-500', 'connection', 'timeout']) {
    await page.getByRole('button', { name: 'Network scenarios', exact: true }).click()
    await page.getByRole('combobox', { name: 'Network scenario', exact: true }).selectOption(scenario)
    await page.getByRole('dialog').getByRole('button', { name: 'Back', exact: true }).click()
    await page.getByRole('tab', { name: 'Ranking', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Unable to load voyages', { timeout: 15000 })
    await page.getByRole('tab', { name: 'Harbor' }).click()
    await page.getByRole('button', { name: 'Options', exact: true }).click()
    await expect(page.getByLabel('Game session time', { exact: true })).toHaveValue('90')
    await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    await expect(page.locator('canvas')).toBeVisible()
    await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Network scenarios', exact: true }).click()
  await page.getByRole('combobox', { name: 'Network scenario', exact: true }).selectOption('slow')
  await page.getByRole('dialog').getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('tab', { name: 'Ranking', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Loading voyages…')
  await expect(page.locator('[data-match-id]')).toHaveCount(5)
})

test('pause Options keeps the current round frozen and applies saved changes to the next round', async ({ page }) => {
  await page.goto('/?scenario=arena')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const before = await page.evaluate('window.__battle.snapshot()')
  await page.getByRole('dialog').getByRole('button', { name: 'Options', exact: true }).click()
  await page.getByRole('button', { name: 'Increase game session time' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Mute sound' }).click()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.evaluate('window.__battle.advance(5)')
  expect(await page.evaluate('window.__battle.snapshot()')).toEqual(before)
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Mute sound' })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate('window.__battle.snapshot().config.duration')).toBe(90)
  await page.evaluate('window.__battle.advance(180)')
  await page.getByRole('button', { name: 'Play Again' }).click()
  await expect(page.locator('canvas')).toBeVisible()
  expect(await page.evaluate('window.__battle.snapshot().config.duration')).toBe(100)
  expect(await page.evaluate('window.__battle.snapshot().elapsed')).toBe(0)
})
