import { expect, test, type Page } from '@playwright/test'

async function scenario(page: Page, value: string) {
  const activeTab = page.getByRole('tab', { selected: true })
  const selected = await activeTab.count() ? await activeTab.textContent() : null
  if (await page.getByRole('tab', { name: 'Harbor' }).count()) await page.getByRole('tab', { name: 'Harbor' }).click()
  await page.getByRole('button', { name: 'Network scenarios', exact: true }).click()
  await page.getByRole('combobox', { name: 'Network scenario', exact: true }).selectOption(value)
  await page.getByRole('dialog').getByRole('button', { name: 'Back', exact: true }).click()
  if (selected === 'Ranking' || selected === 'Match History') await page.getByRole('tab', { name: selected, exact: true }).click()
}
async function complete(page: Page) {
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.evaluate('window.__battle.advance(90)')
  await expect(page.getByRole('heading', { name: 'Battle complete' })).toBeVisible()
}

test('completed match persists, registers once and appears in both tabs', async ({ page }) => {
  await page.goto('/?scenario=time')
  await complete(page)
  await expect(page.getByText('Match registered.', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Last result', exact: true }).click()
  await expect(page.getByText('Points · 01:30 · Time up')).toBeVisible()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.getByRole('tab', { name: 'Match History' }).click()
  await expect(page.locator('[data-match-id]')).toHaveCount(1)
  const id = await page.locator('[data-match-id]').getAttribute('data-match-id')
  await page.getByRole('tab', { name: 'Ranking', exact: true }).click()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator(`[data-match-id="${id}"]`)).toBeVisible()
})

test('post-commit timeout survives refresh and retry without duplication', async ({ page }) => {
  await page.goto('/?scenario=time')
  await scenario(page, 'post-commit-timeout')
  await complete(page)
  await expect(page.getByRole('alert')).toContainText('Registration failed', { timeout: 10000 })
  await page.reload()
  await page.getByRole('button', { name: 'Last result', exact: true }).click()
  await expect(page.getByText('1 match(es) pending registration.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await scenario(page, 'success')
  await page.getByRole('button', { name: 'Last result', exact: true }).click()
  await page.getByRole('button', { name: 'Retry registration' }).dblclick()
  await expect(page.getByText('Match registered.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.getByRole('tab', { name: 'Match History' }).click()
  await expect(page.locator('[data-match-id]')).toHaveCount(1)
})

test('query failures, pagination, empty results and abandoned battles', async ({ page }) => {
  await page.goto('/')
  await scenario(page, 'empty')
  await page.getByRole('tab', { name: 'Ranking', exact: true }).click()
  await expect(page.getByText('No voyages yet.')).toBeVisible()
  await scenario(page, 'ranking-error')
  await expect(page.getByRole('alert')).toContainText('Unable to load voyages')
  await scenario(page, 'pages')
  await expect(page.locator('[data-match-id]')).toHaveCount(5)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('Page 2 of 8')).toBeVisible()
  await scenario(page, 'out-of-order')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('button', { name: 'Previous', exact: true }).click()
  await expect(page.getByText('Page 1 of 2')).toBeVisible()
  await page.getByRole('tab', { name: 'Harbor' }).click()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Last result', exact: true })).toHaveCount(0)
})

test('outage keeps multiple pending matches while allowing another round', async ({ page }) => {
  await page.goto('/?scenario=time')
  await scenario(page, 'outage')
  await complete(page)
  await expect(page.getByRole('alert')).toContainText('Registration failed')
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await complete(page)
  await expect(page.getByText('2 match(es) pending registration.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await scenario(page, 'success')
  await page.getByRole('button', { name: 'Last result', exact: true }).click()
  await page.getByRole('button', { name: 'Retry registration' }).click()
  await expect(page.getByText('Match registered.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.getByRole('tab', { name: 'Match History' }).click()
  await expect(page.locator('[data-match-id]')).toHaveCount(2)
})

test('late reads cannot overwrite the current page and history errors recover', async ({ page }) => {
  await page.goto('/')
  await scenario(page, 'success')
  await page.getByRole('tab', { name: 'Ranking', exact: true }).click()
  await expect(page.locator('[data-match-id]')).toHaveCount(5)
  await scenario(page, 'out-of-order')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('Page 2 of 2')).toBeVisible()
  const ids = await page.locator('[data-match-id]').evaluateAll((elements) => elements.map((element) => element.getAttribute('data-match-id')))
  await page.waitForTimeout(2000)
  expect(await page.locator('[data-match-id]').evaluateAll((elements) => elements.map((element) => element.getAttribute('data-match-id')))).toEqual(ids)
  await scenario(page, 'history-error')
  await page.getByRole('tab', { name: 'Match History', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Unable to load voyages')
  await scenario(page, 'success')
  await expect(page.getByText('No voyages yet.')).toBeVisible()
})
