import { expect, test } from '@playwright/test'

test('validates and persists options, then starts with the saved duration', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Options', exact: true }).click()
  await page.getByLabel('Game session time', { exact: true }).fill('59')
  await page.getByLabel('Enemy spawn time', { exact: true }).fill('0')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByRole('status')).toContainText('Enter a whole session time')
  await page.getByLabel('Game session time', { exact: true }).fill('180')
  await page.getByLabel('Enemy spawn time', { exact: true }).fill('2.5')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByRole('status')).toHaveText('Settings saved.')
  await page.reload()
  await page.getByRole('button', { name: 'Options', exact: true }).click()
  await expect(page.getByLabel('Game session time', { exact: true })).toHaveValue('180')
  await expect(page.getByLabel('Enemy spawn time', { exact: true })).toHaveValue('2.5')
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const [minutes, seconds] = (await page.locator('dl dd').nth(2).innerText()).split(':').map(Number)
  expect(minutes * 60 + seconds).toBeGreaterThan(170)
})

test('battle controls fit after changing to landscape', async ({ page }) => {
  await page.setViewportSize({ width: 393, height: 851 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.setViewportSize({ width: 851, height: 393 })
  await expect.poll(() => page.evaluate<boolean>('document.querySelector(".game-controls").getBoundingClientRect().bottom <= innerHeight')).toBe(true)
})

test('illustrated options steppers save their values when returning to the menu', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Options', exact: true }).click()
  await page.getByRole('button', { name: 'Increase game session time' }).click()
  await page.getByRole('button', { name: 'Decrease enemy spawn time' }).click()
  await expect(page.getByLabel('Game session time', { exact: true })).toHaveValue('100')
  await expect(page.getByLabel('Enemy spawn time', { exact: true })).toHaveValue('3')
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Options', exact: true }).click()
  await expect(page.getByLabel('Game session time', { exact: true })).toHaveValue('100')
  await expect(page.getByLabel('Enemy spawn time', { exact: true })).toHaveValue('3')
})
